name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
      - name: Configure environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
      - run: pip install docker-compose
      - name: Test the app using Docker Compose
        uses: actions/checkout@v1
      - run: docker-compose run app sh -c "python manage.py test && flake8"
