name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
      
      - name: Install docker-compose
        run: pip install docker-compose

      - name: Checkout the repository
        uses: actions/checkout@v1
      
      - name: Build and Test the application
        run: docker-compose run app sh -c "python manage.py test && flake8"
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
